### ISSUE TITLE
OOOOOPSSSS

### ISSUE THREAD

**Issue by GitJakobE** [g3rv4/RandomForest.Sample#1]
I get all OOOPSS in the first and the last test and even 10% Ooops in the classification:
----------------------
Processing line 1 - R prediction: 6,42363333333334E+15 - C#: 1,48480000000007E+15
   OOOOOPSSSSS
processing line 2 - R prediction: 6,22511428571429E+16 - C#: 1,44226666666673E+15
   OOOOOPSSSSS
Processing line 3 - R prediction: 8,65553333333334E+15 - C#: 1,47280000000007E+15
   OOOOOPSSSSS
Processing line 4 - R prediction: 1,46762E+16 - C#: 1,44226666666673E+15
   OOOOOPSSSSS
Processing line 5 - R prediction: 9,3867E+15 - C#: 1,44226666666673E+15
   OOOOOPSSSSS
ect.
----------------------
the lib seem pretty straight forward so I don't see what I could have done wrong.

**Comment by g3rv4** [comment]
hey @GitJakobE! why did you close the issue? I'm curious... I've been wanting to code these as unit tests, but I don't use the lib so it's hard to find the time.

**Comment by GitJakobE** [comment]
Hi. It was a simple setting issue on my windows. As a default here the decimal symbol is a comma and the digit grouping symbol is a dot. The code can be make indifferent in regards to the regional settings but for most coders it will not matter which is why I closed it. Also, I did feel that I should have known it form the extremely large numbers:-)

**Comment by g3rv4** [comment]
ah, that makes sense. Interestingly, I live in a country where we use comma for the decimal symbol, but have all my systems set up to use US standards.

Anyway, thanks for the explanation!
